food/urls.py
from django.urls import path
from food.views import *

app_name="eating"

urlpatterns=[
    path('nonveg/',nonveg,name='nonveg'),
]

shopping/urls.py
from django.urls import path
from shopping.views import *

app_name="grocery"

urlpatterns=[
    path('grocery/',grocery,name='grocery'),
]

swiggy/urls.py
from django.contrib import admin
from django.urls import path,include
import food,shopping

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('shopping/',include('shopping.urls')),
]

food/models.py
from django.db import models

# Create your models here.

shopping/models.py
from django.db import models

# Create your models here.

food/views.py
from django.shortcuts import render

# Create your views here.
def nonveg(request):
    return render(request,'nonveg.html')

shopping/views.py
from django.shortcuts import render

# Create your views here.
def grocery(request):
    return render(request,'grocery.html')

templates/grocery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Groceries</h1>
        <a href="{% url 'eating:nonveg' %}">click here</a>
    </center>
</body>
</html>

templates/nonveg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Chicken biryani</h1>
        <a href="{% url 'grocery:grocery' %}">click for grocery</a>
    </center>
</body>
</html>